### ISSUE TITLE
comm.csv is unusual

### ISSUE THREAD

**Issue by ZYX223** [matthiasdiener/numalize#3]
I have installed the libelf and I try to trace the NPBOMP FT Benchmark, 
and I got the comm.csv,I think it is unusual.
OS is ubuntu 18.04  Pin version is 3.13

2425578 | 3084910 | 5212812 | 6601189 | 4759668 | 0
2702005 | 3172482 | 5930069 | 5428907 | 0 | 4759668
2438581 | 2959521 | 5601134 | 0 | 5428907 | 6601189
2687703 | 3262682 | 0 | 5601134 | 5930069 | 5212812
2797326 | 0 | 3262682 | 2959521 | 3172482 | 3084910
0 | 2797326 | 2687703 | 2438581 | 2702005 | 2425578

do you think it's right?

**Comment by matthiasdiener** [comment]
I don't see anything unusual. What kind of comm.csv did you expect?

**Comment by ZYX223** [comment]
[](url)
